### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ayodelekehinde** [Merkost/Schedule#10]
I couldn't reach you on telegram. Pls I need to know your personal experience with M1 macbook for android development. Especially the 8g ram variation. Thanks

**Comment by Merkost** [comment]
Hello! I was using M1 air 8/256gb for Android development for about a year and my experience is quite ambiguous. It is very thin and lightweight, but it is very controversial to use it when working in large AndroidStudio projects. All runs smoothly, except the build time. It was increasing every time I opened new bigger project. And if in small projects which have about 5-10 screens build time takes about 2-4 minutes, then in such bigger projects it takes about 4-10 and sometimes more minutes to build the application. Besides MacBook was heating up so much, and it just cut CPU performance due to lack of active cooling. If you'll work in big projects I recommend you to choose new MacBook pro 14. 
So 8gb ram was okay, it was always using swap memory, about 2-4 gigs.

Working in big projects makes me move to m1 pro MacBook 14 from air 13 m1

**Comment by ayodelekehinde** [comment]
Thanks for the honesty. Merkost
